[OK]"[OK]"[OK]"[OK][OK]
[OK]E[OK]x[OK]p[OK]e[OK]r[OK]i[OK]m[OK]e[OK]n[OK]t[OK]o[OK] [OK]1[OK]0[OK]:[OK] [OK]M[OK]ú[OK]l[OK]t[OK]i[OK]p[OK]l[OK]a[OK]s[OK] [OK]F[OK]o[OK]n[OK]t[OK]e[OK]s[OK] [OK]R[OK]F[OK] [OK]([OK]M[OK]u[OK]l[OK]t[OK]i[OK]-[OK]S[OK]o[OK]u[OK]r[OK]c[OK]e[OK] [OK]K[OK]e[OK]y[OK] [OK]G[OK]e[OK]n[OK]e[OK]r[OK]a[OK]t[OK]i[OK]o[OK]n[OK])[OK][OK]
[OK][OK]
[OK]B[OK]a[OK]s[OK]e[OK]a[OK]d[OK]o[OK] [OK]e[OK]m[OK] [OK]P[OK]r[OK]o[OK]x[OK]i[OK]M[OK]a[OK]t[OK]e[OK] [OK]([OK]M[OK]a[OK]t[OK]h[OK]u[OK]r[OK] [OK]e[OK]t[OK] [OK]a[OK]l[OK].[OK],[OK] [OK]M[OK]o[OK]b[OK]i[OK]S[OK]y[OK]s[OK] [OK]2[OK]0[OK]1[OK]1[OK])[OK]:[OK][OK]
[OK]-[OK] [OK]M[OK]o[OK]n[OK]i[OK]t[OK]o[OK]r[OK]a[OK] [OK]N[OK] [OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK] [OK]R[OK]F[OK] [OK]i[OK]n[OK]d[OK]e[OK]p[OK]e[OK]n[OK]d[OK]e[OK]n[OK]t[OK]e[OK]s[OK] [OK]s[OK]i[OK]m[OK]u[OK]l[OK]t[OK]a[OK]n[OK]e[OK]a[OK]m[OK]e[OK]n[OK]t[OK]e[OK][OK]
[OK]-[OK] [OK]T[OK]a[OK]x[OK]a[OK] [OK]d[OK]e[OK] [OK]g[OK]e[OK]r[OK]a[OK]ç[OK]ã[OK]o[OK] [OK]=[OK] [OK]N[OK] [OK]×[OK] [OK]t[OK]a[OK]x[OK]a[OK]_[OK]s[OK]i[OK]n[OK]g[OK]l[OK]e[OK]_[OK]s[OK]o[OK]u[OK]r[OK]c[OK]e[OK][OK]
[OK]-[OK] [OK]D[OK]e[OK]m[OK]o[OK]n[OK]s[OK]t[OK]r[OK]a[OK] [OK]e[OK]s[OK]c[OK]a[OK]l[OK]a[OK]b[OK]i[OK]l[OK]i[OK]d[OK]a[OK]d[OK]e[OK] [OK]d[OK]o[OK] [OK]P[OK]K[OK]G[OK][OK]
[OK][OK]
[OK]O[OK]b[OK]j[OK]e[OK]t[OK]i[OK]v[OK]o[OK]s[OK]:[OK][OK]
[OK]1[OK].[OK] [OK]S[OK]i[OK]m[OK]u[OK]l[OK]a[OK]r[OK] [OK]N[OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK] [OK]R[OK]F[OK] [OK]i[OK]n[OK]d[OK]e[OK]p[OK]e[OK]n[OK]d[OK]e[OK]n[OK]t[OK]e[OK]s[OK][OK]
[OK]2[OK].[OK] [OK]P[OK]r[OK]o[OK]c[OK]e[OK]s[OK]s[OK]a[OK]r[OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK] [OK]e[OK]m[OK] [OK]p[OK]a[OK]r[OK]a[OK]l[OK]e[OK]l[OK]o[OK] [OK]p[OK]a[OK]r[OK]a[OK] [OK]g[OK]e[OK]r[OK]a[OK]r[OK] [OK]c[OK]h[OK]a[OK]v[OK]e[OK]s[OK][OK]
[OK]3[OK].[OK] [OK]M[OK]e[OK]d[OK]i[OK]r[OK] [OK]t[OK]a[OK]x[OK]a[OK] [OK]d[OK]e[OK] [OK]g[OK]e[OK]r[OK]a[OK]ç[OK]ã[OK]o[OK] [OK]t[OK]o[OK]t[OK]a[OK]l[OK] [OK]v[OK]s[OK] [OK]n[OK]ú[OK]m[OK]e[OK]r[OK]o[OK] [OK]d[OK]e[OK] [OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK][OK]
[OK]4[OK].[OK] [OK]C[OK]o[OK]m[OK]p[OK]a[OK]r[OK]a[OK]r[OK] [OK]c[OK]o[OK]m[OK] [OK]P[OK]r[OK]o[OK]x[OK]i[OK]M[OK]a[OK]t[OK]e[OK] [OK]([OK]1[OK]0[OK] [OK]F[OK]M[OK] [OK]s[OK]o[OK]u[OK]r[OK]c[OK]e[OK]s[OK] [OK]→[OK] [OK]4[OK]-[OK]d[OK]i[OK]g[OK]i[OK]t[OK] [OK]P[OK]I[OK]N[OK] [OK]e[OK]m[OK] [OK]0[OK].[OK]3[OK]4[OK]s[OK])[OK][OK]
[OK]"[OK]"[OK]"[OK][OK]
[OK][OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]s[OK]y[OK]s[OK][OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]o[OK]s[OK][OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]n[OK]u[OK]m[OK]p[OK]y[OK] [OK]a[OK]s[OK] [OK]n[OK]p[OK][OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK][OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]t[OK]q[OK]d[OK]m[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]t[OK]q[OK]d[OK]m[OK][OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]j[OK]s[OK]o[OK]n[OK][OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]d[OK]a[OK]t[OK]e[OK]t[OK]i[OK]m[OK]e[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]e[OK]t[OK]i[OK]m[OK]e[OK][OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]m[OK]a[OK]t[OK]p[OK]l[OK]o[OK]t[OK]l[OK]i[OK]b[OK].[OK]p[OK]y[OK]p[OK]l[OK]o[OK]t[OK] [OK]a[OK]s[OK] [OK]p[OK]l[OK]t[OK][OK]
[OK][OK]
[OK]#[OK] [OK]A[OK]d[OK]i[OK]c[OK]i[OK]o[OK]n[OK]a[OK] [OK]p[OK]a[OK]t[OK]h[OK] [OK]d[OK]o[OK] [OK]p[OK]r[OK]o[OK]j[OK]e[OK]t[OK]o[OK][OK]
[OK]s[OK]y[OK]s[OK].[OK]p[OK]a[OK]t[OK]h[OK].[OK]i[OK]n[OK]s[OK]e[OK]r[OK]t[OK]([OK]0[OK],[OK] [OK]o[OK]s[OK].[OK]p[OK]a[OK]t[OK]h[OK].[OK]a[OK]b[OK]s[OK]p[OK]a[OK]t[OK]h[OK]([OK]o[OK]s[OK].[OK]p[OK]a[OK]t[OK]h[OK].[OK]j[OK]o[OK]i[OK]n[OK]([OK]o[OK]s[OK].[OK]p[OK]a[OK]t[OK]h[OK].[OK]d[OK]i[OK]r[OK]n[OK]a[OK]m[OK]e[OK]([OK]_[OK]_[OK]f[OK]i[OK]l[OK]e[OK]_[OK]_[OK])[OK],[OK] [OK]'[OK].[OK].[OK]'[OK])[OK])[OK])[OK][OK]
[OK][OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]s[OK]r[OK]c[OK].[OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK]s[OK]_[OK]c[OK]o[OK]r[OK]r[OK]e[OK]t[OK]o[OK]r[OK]e[OK]s[OK].[OK]b[OK]c[OK]h[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]g[OK]e[OK]r[OK]a[OK]r[OK]_[OK]t[OK]a[OK]b[OK]e[OK]l[OK]a[OK]_[OK]c[OK]o[OK]d[OK]i[OK]g[OK]o[OK]s[OK]_[OK]b[OK]c[OK]h[OK],[OK] [OK]g[OK]e[OK]t[OK]_[OK]t[OK]a[OK]m[OK]a[OK]n[OK]h[OK]o[OK]_[OK]b[OK]i[OK]t[OK]s[OK]_[OK]i[OK]n[OK]f[OK]o[OK]r[OK]m[OK]a[OK]c[OK]a[OK]o[OK][OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]s[OK]r[OK]c[OK].[OK]c[OK]a[OK]n[OK]a[OK]l[OK].[OK]c[OK]a[OK]n[OK]a[OK]l[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK]g[OK]e[OK]r[OK]a[OK]r[OK]_[OK]c[OK]s[OK]i[OK]_[OK]c[OK]o[OK]m[OK]p[OK]l[OK]e[OK]x[OK]o[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]p[OK]l[OK]i[OK]c[OK]a[OK]r[OK]_[OK]c[OK]o[OK]r[OK]r[OK]e[OK]l[OK]a[OK]c[OK]a[OK]o[OK]_[OK]c[OK]o[OK]m[OK]p[OK]l[OK]e[OK]x[OK]a[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]g[OK]e[OK]r[OK]a[OK]r[OK]_[OK]c[OK]h[OK]a[OK]v[OK]e[OK]_[OK]d[OK]o[OK]_[OK]c[OK]a[OK]n[OK]a[OK]l[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]g[OK]e[OK]r[OK]a[OK]r[OK]_[OK]c[OK]h[OK]a[OK]v[OK]e[OK]_[OK]l[OK]i[OK]s[OK]t[OK]_[OK]e[OK]n[OK]c[OK]o[OK]d[OK]i[OK]n[OK]g[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]c[OK]o[OK]n[OK]c[OK]i[OK]l[OK]i[OK]a[OK]r[OK]_[OK]l[OK]i[OK]s[OK]t[OK]_[OK]e[OK]n[OK]c[OK]o[OK]d[OK]i[OK]n[OK]g[OK][OK]
[OK])[OK][OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]s[OK]r[OK]c[OK].[OK]p[OK]i[OK]l[OK]a[OK]r[OK]e[OK]s[OK].[OK]r[OK]e[OK]c[OK]o[OK]n[OK]c[OK]i[OK]l[OK]i[OK]a[OK]c[OK]a[OK]o[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]r[OK]e[OK]c[OK]o[OK]n[OK]c[OK]i[OK]l[OK]i[OK]a[OK]r[OK]_[OK]c[OK]h[OK]a[OK]v[OK]e[OK]s[OK][OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]s[OK]r[OK]c[OK].[OK]u[OK]t[OK]i[OK]l[OK].[OK]b[OK]i[OK]n[OK]a[OK]r[OK]i[OK]o[OK]_[OK]u[OK]t[OK]i[OK]l[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]c[OK]o[OK]n[OK]t[OK]a[OK]r[OK]_[OK]e[OK]r[OK]r[OK]o[OK]s[OK]_[OK]b[OK]i[OK]t[OK]s[OK][OK]
[OK][OK]
[OK][OK]
[OK]d[OK]e[OK]f[OK] [OK]s[OK]i[OK]m[OK]u[OK]l[OK]a[OK]r[OK]_[OK]c[OK]a[OK]n[OK]a[OK]l[OK]_[OK]m[OK]u[OK]l[OK]t[OK]i[OK]p[OK]l[OK]o[OK]([OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK],[OK] [OK]t[OK]a[OK]m[OK]a[OK]n[OK]h[OK]o[OK]_[OK]c[OK]s[OK]i[OK],[OK] [OK]r[OK]a[OK]y[OK]l[OK]e[OK]i[OK]g[OK]h[OK]_[OK]p[OK]a[OK]r[OK]a[OK]m[OK],[OK] [OK]c[OK]o[OK]r[OK]r[OK]e[OK]l[OK]a[OK]c[OK]a[OK]o[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK]_[OK]b[OK]o[OK]b[OK],[OK] [OK]e[OK]r[OK]r[OK]o[OK]_[OK]e[OK]s[OK]t[OK]i[OK]m[OK]a[OK]t[OK]i[OK]v[OK]a[OK]=[OK]0[OK].[OK]0[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]S[OK]i[OK]m[OK]u[OK]l[OK]a[OK] [OK]m[OK]ú[OK]l[OK]t[OK]i[OK]p[OK]l[OK]o[OK]s[OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK] [OK]R[OK]F[OK] [OK]i[OK]n[OK]d[OK]e[OK]p[OK]e[OK]n[OK]d[OK]e[OK]n[OK]t[OK]e[OK]s[OK].[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]A[OK]r[OK]g[OK]s[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]:[OK] [OK]N[OK]ú[OK]m[OK]e[OK]r[OK]o[OK] [OK]d[OK]e[OK] [OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK] [OK]R[OK]F[OK] [OK]([OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK] [OK]i[OK]n[OK]d[OK]e[OK]p[OK]e[OK]n[OK]d[OK]e[OK]n[OK]t[OK]e[OK]s[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]a[OK]m[OK]a[OK]n[OK]h[OK]o[OK]_[OK]c[OK]s[OK]i[OK]:[OK] [OK]A[OK]m[OK]o[OK]s[OK]t[OK]r[OK]a[OK]s[OK] [OK]C[OK]S[OK]I[OK] [OK]p[OK]o[OK]r[OK] [OK]f[OK]o[OK]n[OK]t[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]y[OK]l[OK]e[OK]i[OK]g[OK]h[OK]_[OK]p[OK]a[OK]r[OK]a[OK]m[OK]:[OK] [OK]P[OK]a[OK]r[OK]â[OK]m[OK]e[OK]t[OK]r[OK]o[OK] [OK]σ[OK] [OK]d[OK]o[OK] [OK]c[OK]a[OK]n[OK]a[OK]l[OK] [OK]R[OK]a[OK]y[OK]l[OK]e[OK]i[OK]g[OK]h[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]o[OK]r[OK]r[OK]e[OK]l[OK]a[OK]c[OK]a[OK]o[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK]_[OK]b[OK]o[OK]b[OK]:[OK] [OK]C[OK]o[OK]r[OK]r[OK]e[OK]l[OK]a[OK]ç[OK]ã[OK]o[OK] [OK]t[OK]e[OK]m[OK]p[OK]o[OK]r[OK]a[OK]l[OK] [OK]A[OK]l[OK]i[OK]c[OK]e[OK]-[OK]B[OK]o[OK]b[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]e[OK]r[OK]r[OK]o[OK]_[OK]e[OK]s[OK]t[OK]i[OK]m[OK]a[OK]t[OK]i[OK]v[OK]a[OK]:[OK] [OK]E[OK]r[OK]r[OK]o[OK] [OK]d[OK]e[OK] [OK]e[OK]s[OK]t[OK]i[OK]m[OK]a[OK]ç[OK]ã[OK]o[OK] [OK]d[OK]o[OK] [OK]c[OK]a[OK]n[OK]a[OK]l[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]R[OK]e[OK]t[OK]u[OK]r[OK]n[OK]s[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]u[OK]p[OK]l[OK]e[OK]:[OK] [OK]([OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK],[OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]b[OK]o[OK]b[OK],[OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]e[OK]v[OK]e[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]C[OK]a[OK]d[OK]a[OK] [OK]e[OK]l[OK]e[OK]m[OK]e[OK]n[OK]t[OK]o[OK] [OK]é[OK] [OK]l[OK]i[OK]s[OK]t[OK]a[OK] [OK]d[OK]e[OK] [OK]N[OK] [OK]a[OK]r[OK]r[OK]a[OK]y[OK]s[OK] [OK]C[OK]S[OK]I[OK] [OK]c[OK]o[OK]m[OK]p[OK]l[OK]e[OK]x[OK]o[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK] [OK]=[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]b[OK]o[OK]b[OK] [OK]=[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]e[OK]v[OK]e[OK] [OK]=[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]_[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]G[OK]e[OK]r[OK]a[OK] [OK]C[OK]S[OK]I[OK] [OK]p[OK]a[OK]r[OK]a[OK] [OK]A[OK]l[OK]i[OK]c[OK]e[OK] [OK]([OK]f[OK]o[OK]n[OK]t[OK]e[OK] [OK]i[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]h[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK],[OK] [OK]h[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK]_[OK]e[OK]s[OK]t[OK] [OK]=[OK] [OK]g[OK]e[OK]r[OK]a[OK]r[OK]_[OK]c[OK]s[OK]i[OK]_[OK]c[OK]o[OK]m[OK]p[OK]l[OK]e[OK]x[OK]o[OK]([OK]r[OK]a[OK]y[OK]l[OK]e[OK]i[OK]g[OK]h[OK]_[OK]p[OK]a[OK]r[OK]a[OK]m[OK],[OK] [OK]t[OK]a[OK]m[OK]a[OK]n[OK]h[OK]o[OK]_[OK]c[OK]s[OK]i[OK],[OK] [OK]e[OK]r[OK]r[OK]o[OK]_[OK]e[OK]s[OK]t[OK]i[OK]m[OK]a[OK]t[OK]i[OK]v[OK]a[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]B[OK]o[OK]b[OK] [OK]c[OK]o[OK]r[OK]r[OK]e[OK]l[OK]a[OK]c[OK]i[OK]o[OK]n[OK]a[OK]d[OK]o[OK] [OK]t[OK]e[OK]m[OK]p[OK]o[OK]r[OK]a[OK]l[OK]m[OK]e[OK]n[OK]t[OK]e[OK] [OK]c[OK]o[OK]m[OK] [OK]A[OK]l[OK]i[OK]c[OK]e[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]h[OK]_[OK]b[OK]o[OK]b[OK] [OK]=[OK] [OK]a[OK]p[OK]l[OK]i[OK]c[OK]a[OK]r[OK]_[OK]c[OK]o[OK]r[OK]r[OK]e[OK]l[OK]a[OK]c[OK]a[OK]o[OK]_[OK]c[OK]o[OK]m[OK]p[OK]l[OK]e[OK]x[OK]a[OK]([OK]h[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK],[OK] [OK]r[OK]a[OK]y[OK]l[OK]e[OK]i[OK]g[OK]h[OK]_[OK]p[OK]a[OK]r[OK]a[OK]m[OK],[OK] [OK]c[OK]o[OK]r[OK]r[OK]e[OK]l[OK]a[OK]c[OK]a[OK]o[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK]_[OK]b[OK]o[OK]b[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]e[OK]r[OK]r[OK]o[OK]_[OK]e[OK]s[OK]t[OK]i[OK]m[OK]a[OK]t[OK]i[OK]v[OK]a[OK] [OK]>[OK] [OK]0[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]m[OK]p[OK]l[OK]i[OK]t[OK]u[OK]d[OK]e[OK]_[OK]b[OK]o[OK]b[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]a[OK]b[OK]s[OK]([OK]h[OK]_[OK]b[OK]o[OK]b[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]e[OK]r[OK]r[OK]o[OK]_[OK]I[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]n[OK]o[OK]r[OK]m[OK]a[OK]l[OK]([OK]0[OK],[OK] [OK]e[OK]r[OK]r[OK]o[OK]_[OK]e[OK]s[OK]t[OK]i[OK]m[OK]a[OK]t[OK]i[OK]v[OK]a[OK] [OK]*[OK] [OK]a[OK]m[OK]p[OK]l[OK]i[OK]t[OK]u[OK]d[OK]e[OK]_[OK]b[OK]o[OK]b[OK],[OK] [OK]t[OK]a[OK]m[OK]a[OK]n[OK]h[OK]o[OK]_[OK]c[OK]s[OK]i[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]e[OK]r[OK]r[OK]o[OK]_[OK]Q[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]n[OK]o[OK]r[OK]m[OK]a[OK]l[OK]([OK]0[OK],[OK] [OK]e[OK]r[OK]r[OK]o[OK]_[OK]e[OK]s[OK]t[OK]i[OK]m[OK]a[OK]t[OK]i[OK]v[OK]a[OK] [OK]*[OK] [OK]a[OK]m[OK]p[OK]l[OK]i[OK]t[OK]u[OK]d[OK]e[OK]_[OK]b[OK]o[OK]b[OK],[OK] [OK]t[OK]a[OK]m[OK]a[OK]n[OK]h[OK]o[OK]_[OK]c[OK]s[OK]i[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]h[OK]_[OK]b[OK]o[OK]b[OK]_[OK]e[OK]s[OK]t[OK] [OK]=[OK] [OK]h[OK]_[OK]b[OK]o[OK]b[OK] [OK]+[OK] [OK]([OK]e[OK]r[OK]r[OK]o[OK]_[OK]I[OK] [OK]+[OK] [OK]1[OK]j[OK] [OK]*[OK] [OK]e[OK]r[OK]r[OK]o[OK]_[OK]Q[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]e[OK]l[OK]s[OK]e[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]h[OK]_[OK]b[OK]o[OK]b[OK]_[OK]e[OK]s[OK]t[OK] [OK]=[OK] [OK]h[OK]_[OK]b[OK]o[OK]b[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]E[OK]v[OK]e[OK] [OK]d[OK]e[OK]s[OK]c[OK]o[OK]r[OK]r[OK]e[OK]l[OK]a[OK]c[OK]i[OK]o[OK]n[OK]a[OK]d[OK]o[OK] [OK]e[OK]s[OK]p[OK]a[OK]c[OK]i[OK]a[OK]l[OK]m[OK]e[OK]n[OK]t[OK]e[OK] [OK]([OK]c[OK]o[OK]r[OK]r[OK]e[OK]l[OK]a[OK]ç[OK]ã[OK]o[OK] [OK]~[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]h[OK]_[OK]e[OK]v[OK]e[OK],[OK] [OK]h[OK]_[OK]e[OK]v[OK]e[OK]_[OK]e[OK]s[OK]t[OK] [OK]=[OK] [OK]g[OK]e[OK]r[OK]a[OK]r[OK]_[OK]c[OK]s[OK]i[OK]_[OK]c[OK]o[OK]m[OK]p[OK]l[OK]e[OK]x[OK]o[OK]([OK]r[OK]a[OK]y[OK]l[OK]e[OK]i[OK]g[OK]h[OK]_[OK]p[OK]a[OK]r[OK]a[OK]m[OK],[OK] [OK]t[OK]a[OK]m[OK]a[OK]n[OK]h[OK]o[OK]_[OK]c[OK]s[OK]i[OK],[OK] [OK]e[OK]r[OK]r[OK]o[OK]_[OK]e[OK]s[OK]t[OK]i[OK]m[OK]a[OK]t[OK]i[OK]v[OK]a[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]h[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK]_[OK]e[OK]s[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]b[OK]o[OK]b[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]h[OK]_[OK]b[OK]o[OK]b[OK]_[OK]e[OK]s[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]e[OK]v[OK]e[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]h[OK]_[OK]e[OK]v[OK]e[OK]_[OK]e[OK]s[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK],[OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]b[OK]o[OK]b[OK],[OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]e[OK]v[OK]e[OK][OK]
[OK][OK]
[OK][OK]
[OK]d[OK]e[OK]f[OK] [OK]g[OK]e[OK]r[OK]a[OK]r[OK]_[OK]c[OK]h[OK]a[OK]v[OK]e[OK]_[OK]m[OK]u[OK]l[OK]t[OK]i[OK]p[OK]l[OK]a[OK]s[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]([OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]l[OK]i[OK]s[OK]t[OK]a[OK],[OK] [OK]m[OK]e[OK]t[OK]o[OK]d[OK]o[OK]=[OK]'[OK]q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]a[OK]c[OK]a[OK]o[OK]'[OK],[OK] [OK]*[OK]*[OK]k[OK]w[OK]a[OK]r[OK]g[OK]s[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]G[OK]e[OK]r[OK]a[OK] [OK]b[OK]i[OK]t[OK]s[OK] [OK]d[OK]e[OK] [OK]c[OK]h[OK]a[OK]v[OK]e[OK] [OK]d[OK]e[OK] [OK]m[OK]ú[OK]l[OK]t[OK]i[OK]p[OK]l[OK]a[OK]s[OK] [OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK] [OK]R[OK]F[OK].[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]A[OK]r[OK]g[OK]s[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]l[OK]i[OK]s[OK]t[OK]a[OK]:[OK] [OK]L[OK]i[OK]s[OK]t[OK]a[OK] [OK]d[OK]e[OK] [OK]N[OK] [OK]a[OK]r[OK]r[OK]a[OK]y[OK]s[OK] [OK]C[OK]S[OK]I[OK] [OK]c[OK]o[OK]m[OK]p[OK]l[OK]e[OK]x[OK]o[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]m[OK]e[OK]t[OK]o[OK]d[OK]o[OK]:[OK] [OK]'[OK]q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]a[OK]c[OK]a[OK]o[OK]'[OK] [OK]o[OK]u[OK] [OK]'[OK]l[OK]i[OK]s[OK]t[OK]_[OK]e[OK]n[OK]c[OK]o[OK]d[OK]i[OK]n[OK]g[OK]'[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]*[OK]*[OK]k[OK]w[OK]a[OK]r[OK]g[OK]s[OK]:[OK] [OK]A[OK]r[OK]g[OK]u[OK]m[OK]e[OK]n[OK]t[OK]o[OK]s[OK] [OK]a[OK]d[OK]i[OK]c[OK]i[OK]o[OK]n[OK]a[OK]i[OK]s[OK] [OK]p[OK]a[OK]r[OK]a[OK] [OK]m[OK]é[OK]t[OK]o[OK]d[OK]o[OK] [OK]e[OK]s[OK]c[OK]o[OK]l[OK]h[OK]i[OK]d[OK]o[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]R[OK]e[OK]t[OK]u[OK]r[OK]n[OK]s[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]n[OK]d[OK]a[OK]r[OK]r[OK]a[OK]y[OK]:[OK] [OK]B[OK]i[OK]t[OK]s[OK] [OK]c[OK]o[OK]n[OK]c[OK]a[OK]t[OK]e[OK]n[OK]a[OK]d[OK]o[OK]s[OK] [OK]d[OK]e[OK] [OK]t[OK]o[OK]d[OK]a[OK]s[OK] [OK]a[OK]s[OK] [OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]o[OK]u[OK] [OK]t[OK]u[OK]p[OK]l[OK]e[OK]:[OK] [OK]([OK]b[OK]i[OK]t[OK]s[OK],[OK] [OK]i[OK]n[OK]d[OK]i[OK]c[OK]e[OK]s[OK]_[OK]l[OK]i[OK]s[OK]t[OK]a[OK])[OK] [OK]s[OK]e[OK] [OK]l[OK]i[OK]s[OK]t[OK]_[OK]e[OK]n[OK]c[OK]o[OK]d[OK]i[OK]n[OK]g[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]m[OK]e[OK]t[OK]o[OK]d[OK]o[OK] [OK]=[OK]=[OK] [OK]'[OK]q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]a[OK]c[OK]a[OK]o[OK]'[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]i[OK]m[OK]i[OK]a[OK]r[OK] [OK]=[OK] [OK]k[OK]w[OK]a[OK]r[OK]g[OK]s[OK].[OK]g[OK]e[OK]t[OK]([OK]'[OK]l[OK]i[OK]m[OK]i[OK]a[OK]r[OK]'[OK],[OK] [OK]N[OK]o[OK]n[OK]e[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]g[OK]u[OK]a[OK]r[OK]d[OK]_[OK]b[OK]a[OK]n[OK]d[OK] [OK]=[OK] [OK]k[OK]w[OK]a[OK]r[OK]g[OK]s[OK].[OK]g[OK]e[OK]t[OK]([OK]'[OK]g[OK]u[OK]a[OK]r[OK]d[OK]_[OK]b[OK]a[OK]n[OK]d[OK]_[OK]s[OK]i[OK]g[OK]m[OK]a[OK]'[OK],[OK] [OK]0[OK].[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]o[OK]d[OK]o[OK]s[OK]_[OK]b[OK]i[OK]t[OK]s[OK] [OK]=[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]h[OK]_[OK]c[OK]a[OK]n[OK]a[OK]l[OK] [OK]i[OK]n[OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]l[OK]i[OK]s[OK]t[OK]a[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]i[OK]t[OK]s[OK] [OK]=[OK] [OK]g[OK]e[OK]r[OK]a[OK]r[OK]_[OK]c[OK]h[OK]a[OK]v[OK]e[OK]_[OK]d[OK]o[OK]_[OK]c[OK]a[OK]n[OK]a[OK]l[OK]([OK]h[OK]_[OK]c[OK]a[OK]n[OK]a[OK]l[OK],[OK] [OK]g[OK]u[OK]a[OK]r[OK]d[OK]_[OK]b[OK]a[OK]n[OK]d[OK],[OK] [OK]l[OK]i[OK]m[OK]i[OK]a[OK]r[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]o[OK]d[OK]o[OK]s[OK]_[OK]b[OK]i[OK]t[OK]s[OK].[OK]e[OK]x[OK]t[OK]e[OK]n[OK]d[OK]([OK]b[OK]i[OK]t[OK]s[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]n[OK]p[OK].[OK]a[OK]r[OK]r[OK]a[OK]y[OK]([OK]t[OK]o[OK]d[OK]o[OK]s[OK]_[OK]b[OK]i[OK]t[OK]s[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]e[OK]l[OK]i[OK]f[OK] [OK]m[OK]e[OK]t[OK]o[OK]d[OK]o[OK] [OK]=[OK]=[OK] [OK]'[OK]l[OK]i[OK]s[OK]t[OK]_[OK]e[OK]n[OK]c[OK]o[OK]d[OK]i[OK]n[OK]g[OK]'[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]m[OK]i[OK]n[OK]_[OK]s[OK]e[OK]p[OK] [OK]=[OK] [OK]k[OK]w[OK]a[OK]r[OK]g[OK]s[OK].[OK]g[OK]e[OK]t[OK]([OK]'[OK]m[OK]i[OK]n[OK]_[OK]s[OK]e[OK]p[OK]a[OK]r[OK]a[OK]c[OK]a[OK]o[OK]_[OK]s[OK]a[OK]m[OK]p[OK]l[OK]e[OK]s[OK]'[OK],[OK] [OK]1[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]o[OK]d[OK]o[OK]s[OK]_[OK]b[OK]i[OK]t[OK]s[OK] [OK]=[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]o[OK]d[OK]o[OK]s[OK]_[OK]i[OK]n[OK]d[OK]i[OK]c[OK]e[OK]s[OK] [OK]=[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK],[OK] [OK]h[OK]_[OK]c[OK]a[OK]n[OK]a[OK]l[OK] [OK]i[OK]n[OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]l[OK]i[OK]s[OK]t[OK]a[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]i[OK]t[OK]s[OK],[OK] [OK]i[OK]n[OK]d[OK]i[OK]c[OK]e[OK]s[OK] [OK]=[OK] [OK]g[OK]e[OK]r[OK]a[OK]r[OK]_[OK]c[OK]h[OK]a[OK]v[OK]e[OK]_[OK]l[OK]i[OK]s[OK]t[OK]_[OK]e[OK]n[OK]c[OK]o[OK]d[OK]i[OK]n[OK]g[OK]([OK]h[OK]_[OK]c[OK]a[OK]n[OK]a[OK]l[OK],[OK] [OK]m[OK]i[OK]n[OK]_[OK]s[OK]e[OK]p[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]o[OK]d[OK]o[OK]s[OK]_[OK]b[OK]i[OK]t[OK]s[OK].[OK]e[OK]x[OK]t[OK]e[OK]n[OK]d[OK]([OK]b[OK]i[OK]t[OK]s[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]o[OK]d[OK]o[OK]s[OK]_[OK]i[OK]n[OK]d[OK]i[OK]c[OK]e[OK]s[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]([OK]i[OK],[OK] [OK]i[OK]n[OK]d[OK]i[OK]c[OK]e[OK]s[OK])[OK])[OK] [OK] [OK]#[OK] [OK]([OK]f[OK]o[OK]n[OK]t[OK]e[OK]_[OK]i[OK]d[OK],[OK] [OK]i[OK]n[OK]d[OK]i[OK]c[OK]e[OK]s[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]n[OK]p[OK].[OK]a[OK]r[OK]r[OK]a[OK]y[OK]([OK]t[OK]o[OK]d[OK]o[OK]s[OK]_[OK]b[OK]i[OK]t[OK]s[OK])[OK],[OK] [OK]t[OK]o[OK]d[OK]o[OK]s[OK]_[OK]i[OK]n[OK]d[OK]i[OK]c[OK]e[OK]s[OK][OK]
[OK][OK]
[OK][OK]
[OK]d[OK]e[OK]f[OK] [OK]e[OK]x[OK]p[OK]e[OK]r[OK]i[OK]m[OK]e[OK]n[OK]t[OK]o[OK]_[OK]t[OK]a[OK]x[OK]a[OK]_[OK]g[OK]e[OK]r[OK]a[OK]c[OK]a[OK]o[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]_[OK]l[OK]i[OK]s[OK]t[OK]a[OK]=[OK][[OK]1[OK],[OK] [OK]2[OK],[OK] [OK]5[OK],[OK] [OK]1[OK]0[OK]][OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]t[OK]a[OK]m[OK]a[OK]n[OK]h[OK]o[OK]_[OK]c[OK]s[OK]i[OK]=[OK]5[OK]0[OK]0[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]n[OK]u[OK]m[OK]_[OK]i[OK]t[OK]e[OK]r[OK]a[OK]c[OK]o[OK]e[OK]s[OK]=[OK]1[OK]0[OK]0[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]r[OK]r[OK]e[OK]l[OK]a[OK]c[OK]a[OK]o[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK]_[OK]b[OK]o[OK]b[OK]=[OK]0[OK].[OK]9[OK]5[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]a[OK]y[OK]l[OK]e[OK]i[OK]g[OK]h[OK]_[OK]p[OK]a[OK]r[OK]a[OK]m[OK]=[OK]1[OK].[OK]0[OK]/[OK]n[OK]p[OK].[OK]s[OK]q[OK]r[OK]t[OK]([OK]2[OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]e[OK]r[OK]r[OK]o[OK]_[OK]e[OK]s[OK]t[OK]i[OK]m[OK]a[OK]t[OK]i[OK]v[OK]a[OK]=[OK]0[OK].[OK]0[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]g[OK]u[OK]a[OK]r[OK]d[OK]_[OK]b[OK]a[OK]n[OK]d[OK]_[OK]s[OK]i[OK]g[OK]m[OK]a[OK]=[OK]0[OK].[OK]0[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]m[OK]e[OK]t[OK]o[OK]d[OK]o[OK]=[OK]'[OK]q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]a[OK]c[OK]a[OK]o[OK]'[OK][OK]
[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]E[OK]x[OK]p[OK]e[OK]r[OK]i[OK]m[OK]e[OK]n[OK]t[OK]o[OK]:[OK] [OK]T[OK]a[OK]x[OK]a[OK] [OK]d[OK]e[OK] [OK]g[OK]e[OK]r[OK]a[OK]ç[OK]ã[OK]o[OK] [OK]v[OK]s[OK] [OK]n[OK]ú[OK]m[OK]e[OK]r[OK]o[OK] [OK]d[OK]e[OK] [OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK] [OK]R[OK]F[OK].[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]M[OK]e[OK]d[OK]e[OK] [OK]q[OK]u[OK]a[OK]n[OK]t[OK]o[OK]s[OK] [OK]b[OK]i[OK]t[OK]s[OK]/[OK]s[OK]e[OK]g[OK]u[OK]n[OK]d[OK]o[OK] [OK]p[OK]o[OK]d[OK]e[OK]m[OK] [OK]s[OK]e[OK]r[OK] [OK]g[OK]e[OK]r[OK]a[OK]d[OK]o[OK]s[OK] [OK]c[OK]o[OK]m[OK] [OK]N[OK] [OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK].[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]"[OK] [OK]+[OK] [OK]"[OK]=[OK]"[OK]*[OK]8[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]E[OK]X[OK]P[OK]E[OK]R[OK]I[OK]M[OK]E[OK]N[OK]T[OK]O[OK] [OK]1[OK]0[OK]:[OK] [OK]M[OK]Ú[OK]L[OK]T[OK]I[OK]P[OK]L[OK]A[OK]S[OK] [OK]F[OK]O[OK]N[OK]T[OK]E[OK]S[OK] [OK]R[OK]F[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]=[OK]"[OK]*[OK]8[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]M[OK]é[OK]t[OK]o[OK]d[OK]o[OK]:[OK] [OK]{[OK]m[OK]e[OK]t[OK]o[OK]d[OK]o[OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]C[OK]o[OK]r[OK]r[OK]e[OK]l[OK]a[OK]ç[OK]ã[OK]o[OK] [OK]A[OK]l[OK]i[OK]c[OK]e[OK]-[OK]B[OK]o[OK]b[OK]:[OK] [OK]{[OK]c[OK]o[OK]r[OK]r[OK]e[OK]l[OK]a[OK]c[OK]a[OK]o[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK]_[OK]b[OK]o[OK]b[OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]A[OK]m[OK]o[OK]s[OK]t[OK]r[OK]a[OK]s[OK] [OK]C[OK]S[OK]I[OK] [OK]p[OK]o[OK]r[OK] [OK]f[OK]o[OK]n[OK]t[OK]e[OK]:[OK] [OK]{[OK]t[OK]a[OK]m[OK]a[OK]n[OK]h[OK]o[OK]_[OK]c[OK]s[OK]i[OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]I[OK]t[OK]e[OK]r[OK]a[OK]ç[OK]õ[OK]e[OK]s[OK]:[OK] [OK]{[OK]n[OK]u[OK]m[OK]_[OK]i[OK]t[OK]e[OK]r[OK]a[OK]c[OK]o[OK]e[OK]s[OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]G[OK]u[OK]a[OK]r[OK]d[OK] [OK]b[OK]a[OK]n[OK]d[OK] [OK]σ[OK]:[OK] [OK]{[OK]g[OK]u[OK]a[OK]r[OK]d[OK]_[OK]b[OK]a[OK]n[OK]d[OK]_[OK]s[OK]i[OK]g[OK]m[OK]a[OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]=[OK]"[OK]*[OK]8[OK]0[OK] [OK]+[OK] [OK]"[OK]\[OK]n[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK] [OK]=[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]'[OK]:[OK] [OK][[OK]][OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]p[OK]o[OK]r[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]'[OK]:[OK] [OK][[OK]][OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]t[OK]o[OK]t[OK]a[OK]i[OK]s[OK]'[OK]:[OK] [OK][[OK]][OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]b[OK]e[OK]r[OK]_[OK]b[OK]o[OK]b[OK]_[OK]r[OK]a[OK]w[OK]'[OK]:[OK] [OK][[OK]][OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]b[OK]e[OK]r[OK]_[OK]e[OK]v[OK]e[OK]_[OK]r[OK]a[OK]w[OK]'[OK]:[OK] [OK][[OK]][OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]t[OK]e[OK]m[OK]p[OK]o[OK]_[OK]p[OK]r[OK]o[OK]c[OK]e[OK]s[OK]s[OK]a[OK]m[OK]e[OK]n[OK]t[OK]o[OK]'[OK]:[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK] [OK]i[OK]n[OK] [OK]t[OK]q[OK]d[OK]m[OK]([OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]_[OK]l[OK]i[OK]s[OK]t[OK]a[OK],[OK] [OK]d[OK]e[OK]s[OK]c[OK]=[OK]"[OK]T[OK]e[OK]s[OK]t[OK]a[OK]n[OK]d[OK]o[OK] [OK]n[OK]ú[OK]m[OK]e[OK]r[OK]o[OK] [OK]d[OK]e[OK] [OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]"[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]i[OK]t[OK]s[OK]_[OK]p[OK]o[OK]r[OK]_[OK]i[OK]t[OK]e[OK]r[OK]a[OK]c[OK]a[OK]o[OK] [OK]=[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]e[OK]r[OK]_[OK]b[OK]o[OK]b[OK]_[OK]l[OK]i[OK]s[OK]t[OK]a[OK] [OK]=[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]e[OK]r[OK]_[OK]e[OK]v[OK]e[OK]_[OK]l[OK]i[OK]s[OK]t[OK]a[OK] [OK]=[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]e[OK]m[OK]p[OK]o[OK]s[OK] [OK]=[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]_[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]n[OK]u[OK]m[OK]_[OK]i[OK]t[OK]e[OK]r[OK]a[OK]c[OK]o[OK]e[OK]s[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]n[OK]i[OK]c[OK]i[OK]o[OK] [OK]=[OK] [OK]d[OK]a[OK]t[OK]e[OK]t[OK]i[OK]m[OK]e[OK].[OK]n[OK]o[OK]w[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]S[OK]i[OK]m[OK]u[OK]l[OK]a[OK] [OK]m[OK]ú[OK]l[OK]t[OK]i[OK]p[OK]l[OK]o[OK]s[OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK],[OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]b[OK]o[OK]b[OK],[OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]e[OK]v[OK]e[OK] [OK]=[OK] [OK]s[OK]i[OK]m[OK]u[OK]l[OK]a[OK]r[OK]_[OK]c[OK]a[OK]n[OK]a[OK]l[OK]_[OK]m[OK]u[OK]l[OK]t[OK]i[OK]p[OK]l[OK]o[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK],[OK] [OK]t[OK]a[OK]m[OK]a[OK]n[OK]h[OK]o[OK]_[OK]c[OK]s[OK]i[OK],[OK] [OK]r[OK]a[OK]y[OK]l[OK]e[OK]i[OK]g[OK]h[OK]_[OK]p[OK]a[OK]r[OK]a[OK]m[OK],[OK] [OK]c[OK]o[OK]r[OK]r[OK]e[OK]l[OK]a[OK]c[OK]a[OK]o[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK]_[OK]b[OK]o[OK]b[OK],[OK] [OK]e[OK]r[OK]r[OK]o[OK]_[OK]e[OK]s[OK]t[OK]i[OK]m[OK]a[OK]t[OK]i[OK]v[OK]a[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]A[OK]l[OK]i[OK]c[OK]e[OK] [OK]d[OK]e[OK]f[OK]i[OK]n[OK]e[OK] [OK]l[OK]i[OK]m[OK]i[OK]a[OK]r[OK] [OK]c[OK]o[OK]m[OK]p[OK]a[OK]r[OK]t[OK]i[OK]l[OK]h[OK]a[OK]d[OK]o[OK] [OK]([OK]u[OK]s[OK]a[OK] [OK]p[OK]r[OK]i[OK]m[OK]e[OK]i[OK]r[OK]o[OK] [OK]c[OK]a[OK]n[OK]a[OK]l[OK] [OK]c[OK]o[OK]m[OK]o[OK] [OK]r[OK]e[OK]f[OK]e[OK]r[OK]ê[OK]n[OK]c[OK]i[OK]a[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]i[OK]m[OK]i[OK]a[OK]r[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK] [OK]=[OK] [OK]n[OK]p[OK].[OK]m[OK]e[OK]d[OK]i[OK]a[OK]n[OK]([OK]n[OK]p[OK].[OK]a[OK]b[OK]s[OK]([OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK][[OK]0[OK]][OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]G[OK]e[OK]r[OK]a[OK] [OK]b[OK]i[OK]t[OK]s[OK] [OK]d[OK]e[OK] [OK]t[OK]o[OK]d[OK]a[OK]s[OK] [OK]a[OK]s[OK] [OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]m[OK]e[OK]t[OK]o[OK]d[OK]o[OK] [OK]=[OK]=[OK] [OK]'[OK]q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]a[OK]c[OK]a[OK]o[OK]'[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]i[OK]t[OK]s[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK] [OK]=[OK] [OK]g[OK]e[OK]r[OK]a[OK]r[OK]_[OK]c[OK]h[OK]a[OK]v[OK]e[OK]_[OK]m[OK]u[OK]l[OK]t[OK]i[OK]p[OK]l[OK]a[OK]s[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK],[OK] [OK]m[OK]e[OK]t[OK]o[OK]d[OK]o[OK]=[OK]'[OK]q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]a[OK]c[OK]a[OK]o[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]i[OK]m[OK]i[OK]a[OK]r[OK]=[OK]l[OK]i[OK]m[OK]i[OK]a[OK]r[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK],[OK] [OK]g[OK]u[OK]a[OK]r[OK]d[OK]_[OK]b[OK]a[OK]n[OK]d[OK]_[OK]s[OK]i[OK]g[OK]m[OK]a[OK]=[OK]g[OK]u[OK]a[OK]r[OK]d[OK]_[OK]b[OK]a[OK]n[OK]d[OK]_[OK]s[OK]i[OK]g[OK]m[OK]a[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]i[OK]t[OK]s[OK]_[OK]b[OK]o[OK]b[OK] [OK]=[OK] [OK]g[OK]e[OK]r[OK]a[OK]r[OK]_[OK]c[OK]h[OK]a[OK]v[OK]e[OK]_[OK]m[OK]u[OK]l[OK]t[OK]i[OK]p[OK]l[OK]a[OK]s[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]b[OK]o[OK]b[OK],[OK] [OK]m[OK]e[OK]t[OK]o[OK]d[OK]o[OK]=[OK]'[OK]q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]a[OK]c[OK]a[OK]o[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]i[OK]m[OK]i[OK]a[OK]r[OK]=[OK]l[OK]i[OK]m[OK]i[OK]a[OK]r[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK],[OK] [OK]g[OK]u[OK]a[OK]r[OK]d[OK]_[OK]b[OK]a[OK]n[OK]d[OK]_[OK]s[OK]i[OK]g[OK]m[OK]a[OK]=[OK]g[OK]u[OK]a[OK]r[OK]d[OK]_[OK]b[OK]a[OK]n[OK]d[OK]_[OK]s[OK]i[OK]g[OK]m[OK]a[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]i[OK]t[OK]s[OK]_[OK]e[OK]v[OK]e[OK] [OK]=[OK] [OK]g[OK]e[OK]r[OK]a[OK]r[OK]_[OK]c[OK]h[OK]a[OK]v[OK]e[OK]_[OK]m[OK]u[OK]l[OK]t[OK]i[OK]p[OK]l[OK]a[OK]s[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]a[OK]n[OK]a[OK]i[OK]s[OK]_[OK]e[OK]v[OK]e[OK],[OK] [OK]m[OK]e[OK]t[OK]o[OK]d[OK]o[OK]=[OK]'[OK]q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]a[OK]c[OK]a[OK]o[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]i[OK]m[OK]i[OK]a[OK]r[OK]=[OK]N[OK]o[OK]n[OK]e[OK],[OK] [OK]g[OK]u[OK]a[OK]r[OK]d[OK]_[OK]b[OK]a[OK]n[OK]d[OK]_[OK]s[OK]i[OK]g[OK]m[OK]a[OK]=[OK]g[OK]u[OK]a[OK]r[OK]d[OK]_[OK]b[OK]a[OK]n[OK]d[OK]_[OK]s[OK]i[OK]g[OK]m[OK]a[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]A[OK]j[OK]u[OK]s[OK]t[OK]a[OK] [OK]c[OK]o[OK]m[OK]p[OK]r[OK]i[OK]m[OK]e[OK]n[OK]t[OK]o[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]m[OK]i[OK]n[OK]_[OK]l[OK]e[OK]n[OK] [OK]=[OK] [OK]m[OK]i[OK]n[OK]([OK]l[OK]e[OK]n[OK]([OK]b[OK]i[OK]t[OK]s[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK])[OK],[OK] [OK]l[OK]e[OK]n[OK]([OK]b[OK]i[OK]t[OK]s[OK]_[OK]b[OK]o[OK]b[OK])[OK],[OK] [OK]l[OK]e[OK]n[OK]([OK]b[OK]i[OK]t[OK]s[OK]_[OK]e[OK]v[OK]e[OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]i[OK]t[OK]s[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK] [OK]=[OK] [OK]b[OK]i[OK]t[OK]s[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK][[OK]:[OK]m[OK]i[OK]n[OK]_[OK]l[OK]e[OK]n[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]i[OK]t[OK]s[OK]_[OK]b[OK]o[OK]b[OK] [OK]=[OK] [OK]b[OK]i[OK]t[OK]s[OK]_[OK]b[OK]o[OK]b[OK][[OK]:[OK]m[OK]i[OK]n[OK]_[OK]l[OK]e[OK]n[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]i[OK]t[OK]s[OK]_[OK]e[OK]v[OK]e[OK] [OK]=[OK] [OK]b[OK]i[OK]t[OK]s[OK]_[OK]e[OK]v[OK]e[OK][[OK]:[OK]m[OK]i[OK]n[OK]_[OK]l[OK]e[OK]n[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]C[OK]a[OK]l[OK]c[OK]u[OK]l[OK]a[OK] [OK]B[OK]E[OK]R[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]m[OK]i[OK]n[OK]_[OK]l[OK]e[OK]n[OK] [OK]>[OK] [OK]0[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]e[OK]r[OK]_[OK]b[OK]o[OK]b[OK] [OK]=[OK] [OK]c[OK]o[OK]n[OK]t[OK]a[OK]r[OK]_[OK]e[OK]r[OK]r[OK]o[OK]s[OK]_[OK]b[OK]i[OK]t[OK]s[OK]([OK]b[OK]i[OK]t[OK]s[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK],[OK] [OK]b[OK]i[OK]t[OK]s[OK]_[OK]b[OK]o[OK]b[OK])[OK] [OK]/[OK] [OK]m[OK]i[OK]n[OK]_[OK]l[OK]e[OK]n[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]e[OK]r[OK]_[OK]e[OK]v[OK]e[OK] [OK]=[OK] [OK]c[OK]o[OK]n[OK]t[OK]a[OK]r[OK]_[OK]e[OK]r[OK]r[OK]o[OK]s[OK]_[OK]b[OK]i[OK]t[OK]s[OK]([OK]b[OK]i[OK]t[OK]s[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK],[OK] [OK]b[OK]i[OK]t[OK]s[OK]_[OK]e[OK]v[OK]e[OK])[OK] [OK]/[OK] [OK]m[OK]i[OK]n[OK]_[OK]l[OK]e[OK]n[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]i[OK]t[OK]s[OK]_[OK]p[OK]o[OK]r[OK]_[OK]i[OK]t[OK]e[OK]r[OK]a[OK]c[OK]a[OK]o[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]m[OK]i[OK]n[OK]_[OK]l[OK]e[OK]n[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]e[OK]r[OK]_[OK]b[OK]o[OK]b[OK]_[OK]l[OK]i[OK]s[OK]t[OK]a[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]b[OK]e[OK]r[OK]_[OK]b[OK]o[OK]b[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]e[OK]r[OK]_[OK]e[OK]v[OK]e[OK]_[OK]l[OK]i[OK]s[OK]t[OK]a[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]b[OK]e[OK]r[OK]_[OK]e[OK]v[OK]e[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]i[OK]m[OK] [OK]=[OK] [OK]d[OK]a[OK]t[OK]e[OK]t[OK]i[OK]m[OK]e[OK].[OK]n[OK]o[OK]w[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]e[OK]m[OK]p[OK]o[OK]s[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]([OK]f[OK]i[OK]m[OK] [OK]-[OK] [OK]i[OK]n[OK]i[OK]c[OK]i[OK]o[OK])[OK].[OK]t[OK]o[OK]t[OK]a[OK]l[OK]_[OK]s[OK]e[OK]c[OK]o[OK]n[OK]d[OK]s[OK]([OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]E[OK]s[OK]t[OK]a[OK]t[OK]í[OK]s[OK]t[OK]i[OK]c[OK]a[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]'[OK]][OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]t[OK]o[OK]t[OK]a[OK]i[OK]s[OK]'[OK]][OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]n[OK]p[OK].[OK]m[OK]e[OK]a[OK]n[OK]([OK]b[OK]i[OK]t[OK]s[OK]_[OK]p[OK]o[OK]r[OK]_[OK]i[OK]t[OK]e[OK]r[OK]a[OK]c[OK]a[OK]o[OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]p[OK]o[OK]r[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]'[OK]][OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]n[OK]p[OK].[OK]m[OK]e[OK]a[OK]n[OK]([OK]b[OK]i[OK]t[OK]s[OK]_[OK]p[OK]o[OK]r[OK]_[OK]i[OK]t[OK]e[OK]r[OK]a[OK]c[OK]a[OK]o[OK])[OK] [OK]/[OK] [OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]e[OK]r[OK]_[OK]b[OK]o[OK]b[OK]_[OK]r[OK]a[OK]w[OK]'[OK]][OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]1[OK]0[OK]0[OK] [OK]*[OK] [OK]n[OK]p[OK].[OK]m[OK]e[OK]a[OK]n[OK]([OK]b[OK]e[OK]r[OK]_[OK]b[OK]o[OK]b[OK]_[OK]l[OK]i[OK]s[OK]t[OK]a[OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]e[OK]r[OK]_[OK]e[OK]v[OK]e[OK]_[OK]r[OK]a[OK]w[OK]'[OK]][OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]1[OK]0[OK]0[OK] [OK]*[OK] [OK]n[OK]p[OK].[OK]m[OK]e[OK]a[OK]n[OK]([OK]b[OK]e[OK]r[OK]_[OK]e[OK]v[OK]e[OK]_[OK]l[OK]i[OK]s[OK]t[OK]a[OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]t[OK]e[OK]m[OK]p[OK]o[OK]_[OK]p[OK]r[OK]o[OK]c[OK]e[OK]s[OK]s[OK]a[OK]m[OK]e[OK]n[OK]t[OK]o[OK]'[OK]][OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]n[OK]p[OK].[OK]m[OK]e[OK]a[OK]n[OK]([OK]t[OK]e[OK]m[OK]p[OK]o[OK]s[OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]\[OK]n[OK]{[OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]}[OK] [OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]:[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK] [OK] [OK]B[OK]i[OK]t[OK]s[OK] [OK]t[OK]o[OK]t[OK]a[OK]i[OK]s[OK]:[OK] [OK]{[OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]t[OK]o[OK]t[OK]a[OK]i[OK]s[OK]'[OK]][OK][[OK]-[OK]1[OK]][OK]:[OK].[OK]1[OK]f[OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK] [OK] [OK]B[OK]i[OK]t[OK]s[OK]/[OK]f[OK]o[OK]n[OK]t[OK]e[OK]:[OK] [OK]{[OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]p[OK]o[OK]r[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]'[OK]][OK][[OK]-[OK]1[OK]][OK]:[OK].[OK]1[OK]f[OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK] [OK] [OK]B[OK]E[OK]R[OK] [OK]B[OK]o[OK]b[OK]:[OK] [OK]{[OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]e[OK]r[OK]_[OK]b[OK]o[OK]b[OK]_[OK]r[OK]a[OK]w[OK]'[OK]][OK][[OK]-[OK]1[OK]][OK]:[OK].[OK]2[OK]f[OK]}[OK]%[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK] [OK] [OK]B[OK]E[OK]R[OK] [OK]E[OK]v[OK]e[OK]:[OK] [OK]{[OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]e[OK]r[OK]_[OK]e[OK]v[OK]e[OK]_[OK]r[OK]a[OK]w[OK]'[OK]][OK][[OK]-[OK]1[OK]][OK]:[OK].[OK]2[OK]f[OK]}[OK]%[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK] [OK] [OK]T[OK]e[OK]m[OK]p[OK]o[OK]:[OK] [OK]{[OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]t[OK]e[OK]m[OK]p[OK]o[OK]_[OK]p[OK]r[OK]o[OK]c[OK]e[OK]s[OK]s[OK]a[OK]m[OK]e[OK]n[OK]t[OK]o[OK]'[OK]][OK][[OK]-[OK]1[OK]][OK]:[OK].[OK]3[OK]f[OK]}[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][OK]
[OK][OK]
[OK][OK]
[OK]d[OK]e[OK]f[OK] [OK]p[OK]l[OK]o[OK]t[OK]a[OK]r[OK]_[OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK]([OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK],[OK] [OK]f[OK]i[OK]l[OK]e[OK]n[OK]a[OK]m[OK]e[OK]=[OK]N[OK]o[OK]n[OK]e[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]P[OK]l[OK]o[OK]t[OK]a[OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK] [OK]d[OK]o[OK] [OK]e[OK]x[OK]p[OK]e[OK]r[OK]i[OK]m[OK]e[OK]n[OK]t[OK]o[OK].[OK]"[OK]"[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]f[OK]i[OK]l[OK]e[OK]n[OK]a[OK]m[OK]e[OK] [OK]i[OK]s[OK] [OK]N[OK]o[OK]n[OK]e[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]b[OK]a[OK]s[OK]e[OK]_[OK]d[OK]i[OK]r[OK] [OK]=[OK] [OK]o[OK]s[OK].[OK]p[OK]a[OK]t[OK]h[OK].[OK]d[OK]i[OK]r[OK]n[OK]a[OK]m[OK]e[OK]([OK]o[OK]s[OK].[OK]p[OK]a[OK]t[OK]h[OK].[OK]d[OK]i[OK]r[OK]n[OK]a[OK]m[OK]e[OK]([OK]o[OK]s[OK].[OK]p[OK]a[OK]t[OK]h[OK].[OK]a[OK]b[OK]s[OK]p[OK]a[OK]t[OK]h[OK]([OK]_[OK]_[OK]f[OK]i[OK]l[OK]e[OK]_[OK]_[OK])[OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]i[OK]l[OK]e[OK]n[OK]a[OK]m[OK]e[OK] [OK]=[OK] [OK]o[OK]s[OK].[OK]p[OK]a[OK]t[OK]h[OK].[OK]j[OK]o[OK]i[OK]n[OK]([OK]b[OK]a[OK]s[OK]e[OK]_[OK]d[OK]i[OK]r[OK],[OK] [OK]'[OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK]'[OK],[OK] [OK]'[OK]f[OK]i[OK]g[OK]u[OK]r[OK]a[OK]s[OK]'[OK],[OK] [OK]'[OK]e[OK]x[OK]p[OK]1[OK]0[OK]_[OK]m[OK]u[OK]l[OK]t[OK]i[OK]p[OK]l[OK]a[OK]s[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK].[OK]p[OK]n[OK]g[OK]'[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]i[OK]g[OK],[OK] [OK]a[OK]x[OK]e[OK]s[OK] [OK]=[OK] [OK]p[OK]l[OK]t[OK].[OK]s[OK]u[OK]b[OK]p[OK]l[OK]o[OK]t[OK]s[OK]([OK]2[OK],[OK] [OK]2[OK],[OK] [OK]f[OK]i[OK]g[OK]s[OK]i[OK]z[OK]e[OK]=[OK]([OK]1[OK]4[OK],[OK] [OK]1[OK]0[OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]a[OK]x[OK]a[OK] [OK]d[OK]e[OK] [OK]b[OK]i[OK]t[OK]s[OK] [OK]t[OK]o[OK]t[OK]a[OK]i[OK]s[OK] [OK]v[OK]s[OK] [OK]n[OK]ú[OK]m[OK]e[OK]r[OK]o[OK] [OK]d[OK]e[OK] [OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]1[OK] [OK]=[OK] [OK]a[OK]x[OK]e[OK]s[OK][[OK]0[OK],[OK] [OK]0[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]1[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]'[OK]][OK],[OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]t[OK]o[OK]t[OK]a[OK]i[OK]s[OK]'[OK]][OK],[OK] [OK]'[OK]o[OK]-[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]s[OK]i[OK]z[OK]e[OK]=[OK]8[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]1[OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]N[OK]ú[OK]m[OK]e[OK]r[OK]o[OK] [OK]d[OK]e[OK] [OK]F[OK]o[OK]n[OK]t[OK]e[OK]s[OK] [OK]R[OK]F[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]1[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]B[OK]i[OK]t[OK]s[OK] [OK]T[OK]o[OK]t[OK]a[OK]i[OK]s[OK] [OK]G[OK]e[OK]r[OK]a[OK]d[OK]o[OK]s[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]1[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]'[OK]T[OK]a[OK]x[OK]a[OK] [OK]d[OK]e[OK] [OK]G[OK]e[OK]r[OK]a[OK]ç[OK]ã[OK]o[OK] [OK]v[OK]s[OK] [OK]N[OK]ú[OK]m[OK]e[OK]r[OK]o[OK] [OK]d[OK]e[OK] [OK]F[OK]o[OK]n[OK]t[OK]e[OK]s[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]3[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]1[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]E[OK]s[OK]c[OK]a[OK]l[OK]a[OK]b[OK]i[OK]l[OK]i[OK]d[OK]a[OK]d[OK]e[OK] [OK]l[OK]i[OK]n[OK]e[OK]a[OK]r[OK] [OK]([OK]t[OK]e[OK]ó[OK]r[OK]i[OK]c[OK]o[OK] [OK]v[OK]s[OK] [OK]r[OK]e[OK]a[OK]l[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]2[OK] [OK]=[OK] [OK]a[OK]x[OK]e[OK]s[OK][[OK]0[OK],[OK] [OK]1[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]b[OK]i[OK]t[OK]s[OK]_[OK]1[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK] [OK]=[OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]t[OK]o[OK]t[OK]a[OK]i[OK]s[OK]'[OK]][OK][[OK]0[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]t[OK]e[OK]o[OK]r[OK]i[OK]c[OK]o[OK] [OK]=[OK] [OK][[OK]b[OK]i[OK]t[OK]s[OK]_[OK]1[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK] [OK]*[OK] [OK]n[OK] [OK]f[OK]o[OK]r[OK] [OK]n[OK] [OK]i[OK]n[OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]'[OK]][OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]2[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]'[OK]][OK],[OK] [OK]t[OK]e[OK]o[OK]r[OK]i[OK]c[OK]o[OK],[OK] [OK]'[OK]-[OK]-[OK]'[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]T[OK]e[OK]ó[OK]r[OK]i[OK]c[OK]o[OK] [OK]([OK]l[OK]i[OK]n[OK]e[OK]a[OK]r[OK])[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]2[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]'[OK]][OK],[OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]t[OK]o[OK]t[OK]a[OK]i[OK]s[OK]'[OK]][OK],[OK] [OK]'[OK]o[OK]-[OK]'[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]R[OK]e[OK]a[OK]l[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]s[OK]i[OK]z[OK]e[OK]=[OK]8[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]2[OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]N[OK]ú[OK]m[OK]e[OK]r[OK]o[OK] [OK]d[OK]e[OK] [OK]F[OK]o[OK]n[OK]t[OK]e[OK]s[OK] [OK]R[OK]F[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]2[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]B[OK]i[OK]t[OK]s[OK] [OK]T[OK]o[OK]t[OK]a[OK]i[OK]s[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]2[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]'[OK]E[OK]s[OK]c[OK]a[OK]l[OK]a[OK]b[OK]i[OK]l[OK]i[OK]d[OK]a[OK]d[OK]e[OK]:[OK] [OK]T[OK]e[OK]ó[OK]r[OK]i[OK]c[OK]o[OK] [OK]v[OK]s[OK] [OK]R[OK]e[OK]a[OK]l[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]3[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]2[OK].[OK]l[OK]e[OK]g[OK]e[OK]n[OK]d[OK]([OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]1[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]2[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]B[OK]E[OK]R[OK] [OK]v[OK]s[OK] [OK]n[OK]ú[OK]m[OK]e[OK]r[OK]o[OK] [OK]d[OK]e[OK] [OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]3[OK] [OK]=[OK] [OK]a[OK]x[OK]e[OK]s[OK][[OK]1[OK],[OK] [OK]0[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]3[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]'[OK]][OK],[OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]e[OK]r[OK]_[OK]b[OK]o[OK]b[OK]_[OK]r[OK]a[OK]w[OK]'[OK]][OK],[OK] [OK]'[OK]o[OK]-[OK]'[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]B[OK]o[OK]b[OK] [OK]([OK]l[OK]e[OK]g[OK]í[OK]t[OK]i[OK]m[OK]o[OK])[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]s[OK]i[OK]z[OK]e[OK]=[OK]8[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]3[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]'[OK]][OK],[OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]e[OK]r[OK]_[OK]e[OK]v[OK]e[OK]_[OK]r[OK]a[OK]w[OK]'[OK]][OK],[OK] [OK]'[OK]s[OK]-[OK]'[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]E[OK]v[OK]e[OK] [OK]([OK]a[OK]t[OK]a[OK]c[OK]a[OK]n[OK]t[OK]e[OK])[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]s[OK]i[OK]z[OK]e[OK]=[OK]8[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]3[OK].[OK]a[OK]x[OK]h[OK]l[OK]i[OK]n[OK]e[OK]([OK]y[OK]=[OK]5[OK]0[OK],[OK] [OK]c[OK]o[OK]l[OK]o[OK]r[OK]=[OK]'[OK]r[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]s[OK]t[OK]y[OK]l[OK]e[OK]=[OK]'[OK]-[OK]-[OK]'[OK],[OK] [OK]l[OK]a[OK]b[OK]e[OK]l[OK]=[OK]'[OK]C[OK]h[OK]u[OK]t[OK]e[OK] [OK]a[OK]l[OK]e[OK]a[OK]t[OK]ó[OK]r[OK]i[OK]o[OK] [OK]([OK]5[OK]0[OK]%[OK])[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]3[OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]N[OK]ú[OK]m[OK]e[OK]r[OK]o[OK] [OK]d[OK]e[OK] [OK]F[OK]o[OK]n[OK]t[OK]e[OK]s[OK] [OK]R[OK]F[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]3[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]B[OK]E[OK]R[OK] [OK]([OK]%[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]3[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]'[OK]B[OK]E[OK]R[OK]:[OK] [OK]B[OK]o[OK]b[OK] [OK]v[OK]s[OK] [OK]E[OK]v[OK]e[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]3[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]3[OK].[OK]l[OK]e[OK]g[OK]e[OK]n[OK]d[OK]([OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]1[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]3[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]T[OK]e[OK]m[OK]p[OK]o[OK] [OK]d[OK]e[OK] [OK]p[OK]r[OK]o[OK]c[OK]e[OK]s[OK]s[OK]a[OK]m[OK]e[OK]n[OK]t[OK]o[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]4[OK] [OK]=[OK] [OK]a[OK]x[OK]e[OK]s[OK][[OK]1[OK],[OK] [OK]1[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]4[OK].[OK]p[OK]l[OK]o[OK]t[OK]([OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]'[OK]][OK],[OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]t[OK]e[OK]m[OK]p[OK]o[OK]_[OK]p[OK]r[OK]o[OK]c[OK]e[OK]s[OK]s[OK]a[OK]m[OK]e[OK]n[OK]t[OK]o[OK]'[OK]][OK],[OK] [OK]'[OK]o[OK]-[OK]'[OK],[OK] [OK]l[OK]i[OK]n[OK]e[OK]w[OK]i[OK]d[OK]t[OK]h[OK]=[OK]2[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]r[OK]s[OK]i[OK]z[OK]e[OK]=[OK]8[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]4[OK].[OK]s[OK]e[OK]t[OK]_[OK]x[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]N[OK]ú[OK]m[OK]e[OK]r[OK]o[OK] [OK]d[OK]e[OK] [OK]F[OK]o[OK]n[OK]t[OK]e[OK]s[OK] [OK]R[OK]F[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]4[OK].[OK]s[OK]e[OK]t[OK]_[OK]y[OK]l[OK]a[OK]b[OK]e[OK]l[OK]([OK]'[OK]T[OK]e[OK]m[OK]p[OK]o[OK] [OK]d[OK]e[OK] [OK]P[OK]r[OK]o[OK]c[OK]e[OK]s[OK]s[OK]a[OK]m[OK]e[OK]n[OK]t[OK]o[OK] [OK]([OK]s[OK])[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]2[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]4[OK].[OK]s[OK]e[OK]t[OK]_[OK]t[OK]i[OK]t[OK]l[OK]e[OK]([OK]'[OK]O[OK]v[OK]e[OK]r[OK]h[OK]e[OK]a[OK]d[OK] [OK]C[OK]o[OK]m[OK]p[OK]u[OK]t[OK]a[OK]c[OK]i[OK]o[OK]n[OK]a[OK]l[OK]'[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]s[OK]i[OK]z[OK]e[OK]=[OK]1[OK]3[OK],[OK] [OK]f[OK]o[OK]n[OK]t[OK]w[OK]e[OK]i[OK]g[OK]h[OK]t[OK]=[OK]'[OK]b[OK]o[OK]l[OK]d[OK]'[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]x[OK]4[OK].[OK]g[OK]r[OK]i[OK]d[OK]([OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]a[OK]l[OK]p[OK]h[OK]a[OK]=[OK]0[OK].[OK]3[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]l[OK]t[OK].[OK]t[OK]i[OK]g[OK]h[OK]t[OK]_[OK]l[OK]a[OK]y[OK]o[OK]u[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]o[OK]s[OK].[OK]m[OK]a[OK]k[OK]e[OK]d[OK]i[OK]r[OK]s[OK]([OK]o[OK]s[OK].[OK]p[OK]a[OK]t[OK]h[OK].[OK]d[OK]i[OK]r[OK]n[OK]a[OK]m[OK]e[OK]([OK]f[OK]i[OK]l[OK]e[OK]n[OK]a[OK]m[OK]e[OK])[OK],[OK] [OK]e[OK]x[OK]i[OK]s[OK]t[OK]_[OK]o[OK]k[OK]=[OK]T[OK]r[OK]u[OK]e[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]l[OK]t[OK].[OK]s[OK]a[OK]v[OK]e[OK]f[OK]i[OK]g[OK]([OK]f[OK]i[OK]l[OK]e[OK]n[OK]a[OK]m[OK]e[OK],[OK] [OK]d[OK]p[OK]i[OK]=[OK]3[OK]0[OK]0[OK],[OK] [OK]b[OK]b[OK]o[OK]x[OK]_[OK]i[OK]n[OK]c[OK]h[OK]e[OK]s[OK]=[OK]'[OK]t[OK]i[OK]g[OK]h[OK]t[OK]'[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]\[OK]n[OK]✓[OK] [OK]G[OK]r[OK]á[OK]f[OK]i[OK]c[OK]o[OK] [OK]s[OK]a[OK]l[OK]v[OK]o[OK]:[OK] [OK]{[OK]f[OK]i[OK]l[OK]e[OK]n[OK]a[OK]m[OK]e[OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]l[OK]t[OK].[OK]c[OK]l[OK]o[OK]s[OK]e[OK]([OK])[OK][OK]
[OK][OK]
[OK][OK]
[OK]i[OK]f[OK] [OK]_[OK]_[OK]n[OK]a[OK]m[OK]e[OK]_[OK]_[OK] [OK]=[OK]=[OK] [OK]"[OK]_[OK]_[OK]m[OK]a[OK]i[OK]n[OK]_[OK]_[OK]"[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]C[OK]o[OK]n[OK]f[OK]i[OK]g[OK]u[OK]r[OK]a[OK]ç[OK]ã[OK]o[OK][OK]
[OK] [OK] [OK] [OK] [OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]_[OK]l[OK]i[OK]s[OK]t[OK]a[OK] [OK]=[OK] [OK][[OK]1[OK],[OK] [OK]2[OK],[OK] [OK]5[OK],[OK] [OK]1[OK]0[OK],[OK] [OK]2[OK]0[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]E[OK]x[OK]e[OK]c[OK]u[OK]t[OK]a[OK] [OK]e[OK]x[OK]p[OK]e[OK]r[OK]i[OK]m[OK]e[OK]n[OK]t[OK]o[OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK] [OK]=[OK] [OK]e[OK]x[OK]p[OK]e[OK]r[OK]i[OK]m[OK]e[OK]n[OK]t[OK]o[OK]_[OK]t[OK]a[OK]x[OK]a[OK]_[OK]g[OK]e[OK]r[OK]a[OK]c[OK]a[OK]o[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]_[OK]l[OK]i[OK]s[OK]t[OK]a[OK]=[OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]_[OK]l[OK]i[OK]s[OK]t[OK]a[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]a[OK]m[OK]a[OK]n[OK]h[OK]o[OK]_[OK]c[OK]s[OK]i[OK]=[OK]5[OK]0[OK]0[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]n[OK]u[OK]m[OK]_[OK]i[OK]t[OK]e[OK]r[OK]a[OK]c[OK]o[OK]e[OK]s[OK]=[OK]1[OK]0[OK]0[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]o[OK]r[OK]r[OK]e[OK]l[OK]a[OK]c[OK]a[OK]o[OK]_[OK]a[OK]l[OK]i[OK]c[OK]e[OK]_[OK]b[OK]o[OK]b[OK]=[OK]0[OK].[OK]9[OK]5[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]g[OK]u[OK]a[OK]r[OK]d[OK]_[OK]b[OK]a[OK]n[OK]d[OK]_[OK]s[OK]i[OK]g[OK]m[OK]a[OK]=[OK]0[OK].[OK]0[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]m[OK]e[OK]t[OK]o[OK]d[OK]o[OK]=[OK]'[OK]q[OK]u[OK]a[OK]n[OK]t[OK]i[OK]z[OK]a[OK]c[OK]a[OK]o[OK]'[OK][OK]
[OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]S[OK]a[OK]l[OK]v[OK]a[OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]t[OK]i[OK]m[OK]e[OK]s[OK]t[OK]a[OK]m[OK]p[OK] [OK]=[OK] [OK]d[OK]a[OK]t[OK]e[OK]t[OK]i[OK]m[OK]e[OK].[OK]n[OK]o[OK]w[OK]([OK])[OK].[OK]s[OK]t[OK]r[OK]f[OK]t[OK]i[OK]m[OK]e[OK]([OK]"[OK]%[OK]Y[OK]%[OK]m[OK]%[OK]d[OK]_[OK]%[OK]H[OK]%[OK]M[OK]%[OK]S[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]b[OK]a[OK]s[OK]e[OK]_[OK]d[OK]i[OK]r[OK] [OK]=[OK] [OK]o[OK]s[OK].[OK]p[OK]a[OK]t[OK]h[OK].[OK]d[OK]i[OK]r[OK]n[OK]a[OK]m[OK]e[OK]([OK]o[OK]s[OK].[OK]p[OK]a[OK]t[OK]h[OK].[OK]d[OK]i[OK]r[OK]n[OK]a[OK]m[OK]e[OK]([OK]o[OK]s[OK].[OK]p[OK]a[OK]t[OK]h[OK].[OK]a[OK]b[OK]s[OK]p[OK]a[OK]t[OK]h[OK]([OK]_[OK]_[OK]f[OK]i[OK]l[OK]e[OK]_[OK]_[OK])[OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]d[OK]a[OK]d[OK]o[OK]s[OK]_[OK]f[OK]i[OK]l[OK]e[OK] [OK]=[OK] [OK]o[OK]s[OK].[OK]p[OK]a[OK]t[OK]h[OK].[OK]j[OK]o[OK]i[OK]n[OK]([OK]b[OK]a[OK]s[OK]e[OK]_[OK]d[OK]i[OK]r[OK],[OK] [OK]'[OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK]'[OK],[OK] [OK]'[OK]d[OK]a[OK]d[OK]o[OK]s[OK]'[OK],[OK] [OK]f[OK]'[OK]e[OK]x[OK]p[OK]1[OK]0[OK]_[OK]m[OK]u[OK]l[OK]t[OK]i[OK]p[OK]l[OK]a[OK]s[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]_[OK]{[OK]t[OK]i[OK]m[OK]e[OK]s[OK]t[OK]a[OK]m[OK]p[OK]}[OK].[OK]j[OK]s[OK]o[OK]n[OK]'[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]o[OK]s[OK].[OK]m[OK]a[OK]k[OK]e[OK]d[OK]i[OK]r[OK]s[OK]([OK]o[OK]s[OK].[OK]p[OK]a[OK]t[OK]h[OK].[OK]d[OK]i[OK]r[OK]n[OK]a[OK]m[OK]e[OK]([OK]d[OK]a[OK]d[OK]o[OK]s[OK]_[OK]f[OK]i[OK]l[OK]e[OK])[OK],[OK] [OK]e[OK]x[OK]i[OK]s[OK]t[OK]_[OK]o[OK]k[OK]=[OK]T[OK]r[OK]u[OK]e[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]o[OK]p[OK]e[OK]n[OK]([OK]d[OK]a[OK]d[OK]o[OK]s[OK]_[OK]f[OK]i[OK]l[OK]e[OK],[OK] [OK]'[OK]w[OK]'[OK])[OK] [OK]a[OK]s[OK] [OK]f[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]j[OK]s[OK]o[OK]n[OK].[OK]d[OK]u[OK]m[OK]p[OK]([OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK],[OK] [OK]f[OK],[OK] [OK]i[OK]n[OK]d[OK]e[OK]n[OK]t[OK]=[OK]2[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]\[OK]n[OK]✓[OK] [OK]D[OK]a[OK]d[OK]o[OK]s[OK] [OK]s[OK]a[OK]l[OK]v[OK]o[OK]s[OK]:[OK] [OK]{[OK]d[OK]a[OK]d[OK]o[OK]s[OK]_[OK]f[OK]i[OK]l[OK]e[OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]P[OK]l[OK]o[OK]t[OK]a[OK] [OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]l[OK]o[OK]t[OK]a[OK]r[OK]_[OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK]([OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]S[OK]u[OK]m[OK]á[OK]r[OK]i[OK]o[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]"[OK] [OK]+[OK] [OK]"[OK]=[OK]"[OK]*[OK]8[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]S[OK]U[OK]M[OK]Á[OK]R[OK]I[OK]O[OK] [OK]D[OK]O[OK]S[OK] [OK]R[OK]E[OK]S[OK]U[OK]L[OK]T[OK]A[OK]D[OK]O[OK]S[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]=[OK]"[OK]*[OK]8[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]\[OK]n[OK]�[OK]�[OK] [OK]E[OK]s[OK]c[OK]a[OK]l[OK]a[OK]b[OK]i[OK]l[OK]i[OK]d[OK]a[OK]d[OK]e[OK]:[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK] [OK] [OK]1[OK] [OK]f[OK]o[OK]n[OK]t[OK]e[OK]:[OK] [OK] [OK]{[OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]t[OK]o[OK]t[OK]a[OK]i[OK]s[OK]'[OK]][OK][[OK]0[OK]][OK]:[OK].[OK]0[OK]f[OK]}[OK] [OK]b[OK]i[OK]t[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK] [OK] [OK]1[OK]0[OK] [OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]:[OK] [OK]{[OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]t[OK]o[OK]t[OK]a[OK]i[OK]s[OK]'[OK]][OK][[OK]3[OK]][OK]:[OK].[OK]0[OK]f[OK]}[OK] [OK]b[OK]i[OK]t[OK]s[OK] [OK]([OK]{[OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]t[OK]o[OK]t[OK]a[OK]i[OK]s[OK]'[OK]][OK][[OK]3[OK]][OK]/[OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]t[OK]o[OK]t[OK]a[OK]i[OK]s[OK]'[OK]][OK][[OK]0[OK]][OK]:[OK].[OK]1[OK]f[OK]}[OK]x[OK])[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK] [OK] [OK]2[OK]0[OK] [OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]:[OK] [OK]{[OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]t[OK]o[OK]t[OK]a[OK]i[OK]s[OK]'[OK]][OK][[OK]4[OK]][OK]:[OK].[OK]0[OK]f[OK]}[OK] [OK]b[OK]i[OK]t[OK]s[OK] [OK]([OK]{[OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]t[OK]o[OK]t[OK]a[OK]i[OK]s[OK]'[OK]][OK][[OK]4[OK]][OK]/[OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]t[OK]o[OK]t[OK]a[OK]i[OK]s[OK]'[OK]][OK][[OK]0[OK]][OK]:[OK].[OK]1[OK]f[OK]}[OK]x[OK])[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]\[OK]n[OK]�[OK]�[OK] [OK]S[OK]e[OK]g[OK]u[OK]r[OK]a[OK]n[OK]ç[OK]a[OK] [OK]([OK]B[OK]E[OK]R[OK] [OK]E[OK]v[OK]e[OK])[OK]:[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK],[OK] [OK]n[OK] [OK]i[OK]n[OK] [OK]e[OK]n[OK]u[OK]m[OK]e[OK]r[OK]a[OK]t[OK]e[OK]([OK]n[OK]u[OK]m[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]_[OK]l[OK]i[OK]s[OK]t[OK]a[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK] [OK] [OK]{[OK]n[OK]}[OK] [OK]f[OK]o[OK]n[OK]t[OK]e[OK]s[OK]:[OK] [OK]{[OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]e[OK]r[OK]_[OK]e[OK]v[OK]e[OK]_[OK]r[OK]a[OK]w[OK]'[OK]][OK][[OK]i[OK]][OK]:[OK].[OK]1[OK]f[OK]}[OK]%[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]\[OK]n[OK]⚡[OK] [OK]P[OK]e[OK]r[OK]f[OK]o[OK]r[OK]m[OK]a[OK]n[OK]c[OK]e[OK]:[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK] [OK] [OK]B[OK]i[OK]t[OK]s[OK]/[OK]f[OK]o[OK]n[OK]t[OK]e[OK] [OK]c[OK]o[OK]n[OK]s[OK]t[OK]a[OK]n[OK]t[OK]e[OK]:[OK] [OK]{[OK]n[OK]p[OK].[OK]m[OK]e[OK]a[OK]n[OK]([OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]p[OK]o[OK]r[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]'[OK]][OK])[OK]:[OK].[OK]1[OK]f[OK]}[OK] [OK]±[OK] [OK]{[OK]n[OK]p[OK].[OK]s[OK]t[OK]d[OK]([OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]p[OK]o[OK]r[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]'[OK]][OK])[OK]:[OK].[OK]1[OK]f[OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK] [OK] [OK]E[OK]s[OK]c[OK]a[OK]l[OK]a[OK]b[OK]i[OK]l[OK]i[OK]d[OK]a[OK]d[OK]e[OK] [OK]l[OK]i[OK]n[OK]e[OK]a[OK]r[OK]:[OK] [OK]✅[OK]"[OK] [OK]i[OK]f[OK] [OK]n[OK]p[OK].[OK]s[OK]t[OK]d[OK]([OK]r[OK]e[OK]s[OK]u[OK]l[OK]t[OK]a[OK]d[OK]o[OK]s[OK][[OK]'[OK]b[OK]i[OK]t[OK]s[OK]_[OK]p[OK]o[OK]r[OK]_[OK]f[OK]o[OK]n[OK]t[OK]e[OK]'[OK]][OK])[OK] [OK]<[OK] [OK]1[OK]0[OK] [OK]e[OK]l[OK]s[OK]e[OK] [OK]"[OK] [OK] [OK]E[OK]s[OK]c[OK]a[OK]l[OK]a[OK]b[OK]i[OK]l[OK]i[OK]d[OK]a[OK]d[OK]e[OK] [OK]l[OK]i[OK]n[OK]e[OK]a[OK]r[OK]:[OK] [OK]❌[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]"[OK] [OK]+[OK] [OK]"[OK]=[OK]"[OK]*[OK]8[OK]0[OK])[OK][OK]
[OK]